// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATxYWozpScPYD2ssyeWx0LBDt3DnYrbUk',
    appId: '1:579643748294:web:297af246f27c5c9bdf0cc7',
    messagingSenderId: '579643748294',
    projectId: 'messify-flutter',
    authDomain: 'messify-flutter.firebaseapp.com',
    storageBucket: 'messify-flutter.firebasestorage.app',
    measurementId: 'G-E479RCL8WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCseZOQg7tDdizV6Pv51Z4dU2c041QXTL8',
    appId: '1:579643748294:android:01bdbc48426f9975df0cc7',
    messagingSenderId: '579643748294',
    projectId: 'messify-flutter',
    storageBucket: 'messify-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKtOBYi9ktd1zCF357cDczYBSppe8qS1s',
    appId: '1:579643748294:ios:f97e7ea14b3ea9f8df0cc7',
    messagingSenderId: '579643748294',
    projectId: 'messify-flutter',
    storageBucket: 'messify-flutter.firebasestorage.app',
    iosBundleId: 'com.example.messify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKtOBYi9ktd1zCF357cDczYBSppe8qS1s',
    appId: '1:579643748294:ios:f97e7ea14b3ea9f8df0cc7',
    messagingSenderId: '579643748294',
    projectId: 'messify-flutter',
    storageBucket: 'messify-flutter.firebasestorage.app',
    iosBundleId: 'com.example.messify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATxYWozpScPYD2ssyeWx0LBDt3DnYrbUk',
    appId: '1:579643748294:web:096ccfbb097a74d6df0cc7',
    messagingSenderId: '579643748294',
    projectId: 'messify-flutter',
    authDomain: 'messify-flutter.firebaseapp.com',
    storageBucket: 'messify-flutter.firebasestorage.app',
    measurementId: 'G-2ZHQ2LFZ1V',
  );

}