name: messify_owner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.4.5
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  fl_chart: ^0.69.0
  intl: ^0.18.0 
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0 
  flutter_slidable: ^3.1.1 
  qr_flutter: ^4.1.0
  rating_summary: ^1.0.3+1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/messify.png
    - assets/loginpage.jpeg
    - assets/loginfinal.png
    - assets/thali.jpeg
    - assets/mess1.jpeg
    - assets/reg.jpeg
    - assets/avtar.jpeg
    - assets/attendence.jpeg
    - assets/poll.png
    - assets/subcription.png
    - assets/loginscreen.png
    - assets/thali.png
    - assets/daltadka.png
    - assets/demo-image1.png
    - assets/demo-image2.png
    
