name: messify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  cloud_firestore: ^5.4.5
  firebase_auth: ^5.3.1
  firebase_core: ^3.7.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  lottie: ^3.1.3
  path: ^1.9.0
  permission_handler: ^11.3.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.3.3
  sqflite: ^2.3.3+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/messify.png
    - assets/loginpage.jpeg
    - assets/loginfinal.png
    - assets/thali.jpeg
    - assets/mess1.jpeg
    - assets/reg.jpeg
    - assets/mealmanage.png
    - assets/feedback.jpeg
    - assets/avtar.png
    - assets/foodloader.json
    - assets/login.json
    - assets/notification.json

